name: Check Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  check:
    uses: reqstool/.github/.github/workflows/check-semantic-pr.yml@039a28358c4382e178d628c70d899888edd9ddcd # main 2026-03-07
